// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlussnpfeyrejfkzorjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdXNzbnBmZXlyZWpma3pvcmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjI2MzMsImV4cCI6MjA2MzgzODYzM30.jJMuiieHJu6OE1A0D05Cf8idzTpnv7EZou4UhLsr4T4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);